version: '3.1'
services:
  db:
    image: postgis/postgis:14-master
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./csv:/csv
      - ./data:/var/lib/postgresql/data
